use mediconcen_demo;

-- Reset all tables
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE CONSULTATION_FOLLOW_UP;
TRUNCATE CONSULTATION_MEDICATION;
TRUNCATE CONSULTATION_DIAGNOSIS;
TRUNCATE CONSULTATION_INFO;
TRUNCATE MEDICATION_INFO;
TRUNCATE DIAGNOSIS_INFO;
TRUNCATE PATIENT_INFO;
TRUNCATE DOCTOR_INFO;
TRUNCATE CLINIC_INFO;
TRUNCATE USER_INFO;
SET FOREIGN_KEY_CHECKS = 1;

-- Admin User
INSERT INTO USER_INFO (EMAIL, ENCRYPTED_PASSWORD, PHONE_NO, ADDRESS)
VALUES ('admin@mediconcen.com', '$2a$10$OiqggMgFcFxGemo/BujxMOsYPr7wVO5QBZJdF2ogKLVR7yYRuspyO', '12345678', 'Hong Kong');