create database mediconcen_demo;
use mediconcen_demo;

create table USER_INFO
(
  USER_ID           BIGINT AUTO_INCREMENT,
  EMAIL             VARCHAR(255) UNIQUE,
  ENCRYPTED_PASSWORD VARCHAR(128),
  PHONE_NO			BIGINT,
  ADDRESS		    VARCHAR(255),
  PRIMARY KEY (USER_ID)
);


create table CLINIC_INFO
(
    CLINIC_ID       BIGINT AUTO_INCREMENT,
    CLINIC_NAME     VARCHAR(255) UNIQUE,
    PRIMARY KEY (CLINIC_ID)
);


create table DOCTOR_INFO
(
    DOCTOR_ID       BIGINT AUTO_INCREMENT,
    DOCTOR_NAME     VARCHAR(255),
    PRIMARY KEY (DOCTOR_ID)
);


create table PATIENT_INFO
(
    PATIENT_ID      BIGINT AUTO_INCREMENT,
    PATIENT_NAME    VARCHAR(255),
    PRIMARY KEY (PATIENT_ID)
);


create table DIAGNOSIS_INFO
(
    DIAGNOSIS_ID    BIGINT AUTO_INCREMENT,
    DIAGNOSIS_NAME  VARCHAR(255),
    PRIMARY KEY (DIAGNOSIS_ID)
);


create table MEDICATION_INFO
(
    MEDICATION_ID   BIGINT AUTO_INCREMENT,
    MEDICATION_NAME VARCHAR(255),
    PRIMARY KEY (MEDICATION_ID)
);


create table CONSULTATION_INFO
(
    CONSULTATION_ID     BIGINT AUTO_INCREMENT,
    CLINIC_ID           BIGINT,
    DOCTOR_ID           BIGINT,
    PATIENT_ID          BIGINT,
    DATE_TIME           BIGINT,
    CONSULTATION_FEE    DECIMAL(10, 3),
    PRIMARY KEY (CONSULTATION_ID),
    FOREIGN KEY (CLINIC_ID) REFERENCES CLINIC_INFO(CLINIC_ID),
    FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTOR_INFO(DOCTOR_ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT_INFO(PATIENT_ID)
);


create table CONSULTATION_DIAGNOSIS
(
    CONSULTATION_ID BIGINT,
    DIAGNOSIS_ID    BIGINT,
    PRIMARY KEY (CONSULTATION_ID, DIAGNOSIS_ID),
    FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION_INFO(CONSULTATION_ID),
    FOREIGN KEY (DIAGNOSIS_ID) REFERENCES DIAGNOSIS_INFO(DIAGNOSIS_ID)
);


create table CONSULTATION_MEDICATION
(
    CONSULTATION_ID BIGINT,
    MEDICATION_ID   BIGINT,
    PRIMARY KEY (CONSULTATION_ID, MEDICATION_ID),
    FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION_INFO(CONSULTATION_ID),
    FOREIGN KEY (MEDICATION_ID) REFERENCES MEDICATION_INFO(MEDICATION_ID)
);


create table CONSULTATION_FOLLOW_UP
(
    CONSULTATION_ID         BIGINT,
    NEXT_CONSULTATION_ID    BIGINT,
    PRIMARY KEY (CONSULTATION_ID, NEXT_CONSULTATION_ID),
    FOREIGN KEY (CONSULTATION_ID) REFERENCES CONSULTATION_INFO(CONSULTATION_ID),
    FOREIGN KEY (NEXT_CONSULTATION_ID) REFERENCES CONSULTATION_INFO(CONSULTATION_ID)
);

